# Numpy
To efficiently work with arrays in python\
To perform advanced math operations on numeric arrays
## Why numpy
1. Memory efficient:
```Stored in contiguous memory locations```
2. Performance:
```Build on top of C APIs```
3. Array operations:
```Vectorization``` ```Broadcasting```
4. Multi-dimensional support:
```For advanced slicing techniques```
5. Built-in math functions:
```For computing advanced math functions on arrays```
6. Interoperability with other libs:
```Numpy is the building block of libs such as pandas, scipy, matplotlib etc.```

## `ndarray`
The array object in NumPy is called `ndarray`.\
We can create a NumPy ndarray object by using the `numpy.array()` function.\
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray.

### Axis in ndArrays
`axis=0` denotes highest dimension\
`axis=1` denotes second highest dimension\
and so on...
* In case of **1D Array** : `axis=0` denotes cols/elements
* In case of **2D Array** :\
`axis=0` denotes rows and\
`axis-1` denotes cols/elements in each row\
* In case of **3D Array** :
`axis=0` denotes depth\
`axis=1` denotes rows in each depth\
`axis=2` denotes elements in each row


In [1]:
import numpy as np

## Create a numpy array
Syntax: ```np.array(iterable_object, dtype='data-type'<str>, ndmin=dimension<int>)```\
Numpy arrays are generally termed as `ndArray`

In [ ]:
arr = np.array([(1, 2, 3, 4), (5, 6, 7, 8)], dtype='int16', ndmin=2)

print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [8]:
arr_0d = np.array(3) # scalar
arr_1d = np.array([1, 2, 3, 4, 5, 6]) # vector
arr_2d = np.array([(1, 2, 3), (4, 5, 6)]) # matrix
arr_3d = np.array([
    [(1, 2, 3), (4, 5, 6)],
    [(1, 2, 3), (4, 5, 6)],
    [(1, 2, 3), (4, 5, 6)]
]) # 3d tensor

arr_3d.ndim

3

## Inspecting the array

In [ ]:
# number of elements in first dimension
len(arr)

# total number of elements in array
arr.size

8

In [ ]:
# number of dimensions
arr.ndim

2

In [ ]:
# shape of array
arr.shape

(2, 4)

In [ ]:
# datatype object
arr.dtype

# datatype value of element
arr.dtype.name

'int16'

In [ ]:
# converting array into different type
arr_float = arr.astype(float)

arr_float.dtype.name

'float64'

## Accessing array elements

In [ ]:
print(arr_0d) # 0d array

print(arr_1d[2]) # 1d array

print(arr_2d[0, 2]) # 2d array

print(arr_3d[0, 0, 2]) # 3d array

3
3
3
3


Subsetting

In [ ]:
# negative indexing

print(arr_2d[-1, -2])

print(arr_3d[-2, -1, -2])

5
5


Slicing

In [ ]:
# accessing with specified range [start: stop: step]

print(arr_2d[-1, 0:3:2])

print(arr_3d[1:, 0:, -1])

[4 6]
[[3 6]
 [3 6]]


In [ ]:
arr_2d[0:1, :] # all elements in specified row range

arr_3d[:, :, :] # all elements in each dimension

arr_3d[1, :, :] # all elements in dimension 1
arr_3d[1, ... ] # alternate syntax

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# replacing values
print(arr_2d)

arr_2d[-1, 0] = 9 # replace single value
print(arr_2d)

arr_2d[0, 1:] = 8 # replace range of values
print(arr_2d)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [9 5 6]]
[[1 8 8]
 [9 5 6]]


Boolean indexing

In [ ]:
arr_2d[arr_2d == 6]

arr_2d[arr_2d >= 3]

array([3, 4, 5, 6])

## Initializing different types of arrays

In [ ]:
# Array with zeros: shape: (2, 3, 4)
zeros = np.zeros((2, 3, 4), dtype='int32')

print(zeros)

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


In [ ]:
# Array with ones; shape: (2,3)
ones = np.ones((2,3), dtype='float')

print(ones)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Array with specified number; shape: (2, 2)
any_n = np.full((2, 2), 99)

print(any_n)

[[99 99]
 [99 99]]


In [ ]:
# Identity matrix
id_m = np.identity(3)

print(id_m)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# Zero array with kth diagonal as ones
k = 1
zeroK = np.eye(3, 5, k)

print(zeroK)

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [5]:
# Array with random values
arr_rand = np.random.random((3,3)) # random float value between 0 & 1

arr_randint = np.random.randint(-50, 50, (2, 3)) # random value in a range

print(arr_rand, arr_randint, sep='\n')

[[0.99439681 0.04888534 0.60313203]
 [0.72430477 0.30754248 0.20006266]
 [0.70384932 0.92485599 0.63873293]]
[[-32  10 -39]
 [-17  -2   3]]


In [6]:
# Array with empty(-inf) values
arr_empty = np.empty((2, 3))

print(arr_empty)

[[     nan 2.2e-322 1.5e-323]
 [     nan      nan 1.2e-322]]


In [12]:
# Array with repeated elements
print(np.repeat(arr_2d, 3, axis=0)) # repeat rows

print()

print(np.repeat(arr_2d, 5, axis=1)) # repeat cols (inside values)


[[1 2 3]
 [1 2 3]
 [1 2 3]
 [4 5 6]
 [4 5 6]
 [4 5 6]]

[[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3]
 [4 4 4 4 4 5 5 5 5 5 6 6 6 6 6]]


In [18]:
a_1d = [2, 3, 4, 5]

a_3d = [
       [[1, 2, 3],
        [4, 5, 6]],
       [[2, 3, 4],
        [5, 6, 7]],
       [[3, 4, 5],
        [6, 7, 8]]
       ]

np.repeat(0, 2, axis=0)


array([0, 0])

### Initialize the matrix

```
1  1  1  1  1
1  0  0  0  1
1  0  9  0  1
1  0  0  0  1
1  1  1  1  1
```

In [21]:
out = np.ones((5, 5))
out[1:4, 1:4] = np.zeros((3, 3))
out[2, 2] = 5

print(out)

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

## Copying arrays

In [ ]:
# copy() method creates a copy at a location and returns the pointer
# modifications in either arrays would not affect the other

arr = np.array([1, 2, 3, 4, 5, 6])

arr_cpy = arr.copy()
print(arr_cpy)

arr[0] = 8
arr_cpy[5] = 8

print(arr_cpy, arr)

[1 2 3 4 5 6]
[1 2 3 4 5 8] [8 2 3 4 5 6]


In [ ]:
# view() method creates a pointer pointing to the original array
# any modification in either array will affect the other array

arr = np.array([1, 2, 3, 4, 5, 6])

arr_view = arr.view()
print(arr_view)

arr[0] = 8
arr_view[5] = 8

print(arr_view, arr)

[1 2 3 4 5 6]
[8 2 3 4 5 8] [8 2 3 4 5 8]


## Mathematic operations


In [35]:
a = np.array([(1, 2, 3), (4, 5, 6)])
b = np.array([(4, 5, 6), (1, 2, 3)])

In [ ]:
# addition
print(a + b)

np.add(a, b)

[[5 7 9]
 [5 7 9]]


array([[5, 7, 9],
       [5, 7, 9]])

In [ ]:
# substraction
print(a - b)

np.subtract(a, b)

[[-3 -3 -3]
 [ 3  3  3]]


array([[-3, -3, -3],
       [ 3,  3,  3]])

In [39]:
# multiplication (multiplying each corresponding elements)
a1 = np.array([[1, 2, 3], [4, 5, 6]])
b1 = np.array([1, 2, 3])

print(a1.shape, b1.shape)

# Operator overloading: `*`
# if a&b have same shape, element-wise multiplication
# if shape of a: (x, y) and shape of b: (y,);
#   element-wise multiply, with broadcasting
print(a * b)
print(a1 * b1)

print(np.multiply(a, b))
print(np.multiply(a1, b1))

# `*` and `np.multiply()` implies the same meaning

(2, 3) (3,)
[[ 4 10 18]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]
[[ 4 10 18]
 [ 4 10 18]]
[[ 1  4  9]
 [ 4 10 18]]


In [27]:
# division (dividing each corresponding elements)
print(a / b)
print(a1 / b1)

np.divide(a, b)

[[0.25 0.4  0.5 ]
 [4.   2.5  2.  ]]
[[1.         2.         3.        ]
 [0.5        1.         1.5       ]
 [0.33333333 0.66666667 1.        ]]


array([[0.25, 0.4 , 0.5 ],
       [4.  , 2.5 , 2.  ]])

In [ ]:
# squareroot and exponentiation [e^i]
a = np.array([4, 9, 16])

print(np.sqrt(a))
print(np.exp(a))

[2. 3. 4.]
[5.45981500e+01 8.10308393e+03 8.88611052e+06]


In [ ]:
# trigonometric and logarithmic functions

a = np.array([30, 60, 90]) # angles in degrees

print(np.sin(np.radians(a)))
print(np.cos(np.radians(a)))
print(np.log(a)) # natural logarithm (base e)

[0.5       0.8660254 1.       ]
[8.66025404e-01 5.00000000e-01 6.12323400e-17]
[3.40119738 4.09434456 4.49980967]


In [ ]:
# dot product

a = np.array([1, 2, 1])
b = np.array([4, 5, 6])

a.dot(b)

20

## Linear Algebra

In [ ]:
# trace of a matrix
a = np.identity(3)

np.trace(a)

3.0

In [40]:
# matrix multiplication
a = np.ones((2, 3))
b = np.full((3, 4), 4)

print(np.matmul(a, b))

[[12. 12. 12. 12.]
 [12. 12. 12. 12.]]


In [42]:
# determinant of matrix
a = np.identity(3)

print(np.linalg.det(a))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
1.0


In [ ]:
# eigen values and eigen vectors
a = np.full((2, 2), 3)

np.linalg.eig(a).eigenvalues
np.linalg.eig(a).eigenvectors

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [ ]:
# inverse of a matrix
a = np.identity(3)

np.linalg.inv(a)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Statistics

Most functions in this section consider \
`axis=0` as `col`\
`axis=1` as `row`

In [ ]:
# min and max
a = np.random.randint(-10, 25, (3, 4))
print(a)

print()
print(np.min(a, axis=0)) # min value in col
print(np.max(a, axis=1)) # max value in row

[[18  8  5  2]
 [16  6 -1 10]
 [20 -8 15 -1]]

[16 -8 -1 -1]
[18 16 20]


In [ ]:
# sum of elements
a = np.random.randint(-10, 25, (3, 4))
print(a)

print()
print(np.sum(a, axis=0)) # sum elements in same col
print(np.sum(a, axis=1)) # sum elements in same row

[[10  9 -3 -4]
 [ 8  4 -7 14]
 [-8  6  7 12]]

[10 19 -3 22]
[12 19 17]


In [ ]:
# measures of central tendencies: mean & median
a = np.random.randint(-20, 30, (4, 4))
print(a)

print()
print(np.mean(a, axis=0))
print(np.median(a, axis=1))

[[  5  19 -11  25]
 [ 13   8  28  24]
 [-12  25 -17   5]
 [ 20  16  -3  -8]]

[ 6.5  17.   -0.75 11.5 ]
[12.  18.5 -3.5  6.5]


In [ ]:
# cumulative sum of each row or col
a = np.random.randint(-20, 30, (4, 4))
print(a)

print()
print(np.cumsum(a, axis=0))
print(np.cumsum(a, axis=1))

[[ 12  -9  27   1]
 [-18  14  -7 -10]
 [ -6   2   5  17]
 [ 27  -2 -18  15]]

[[ 12  -9  27   1]
 [ -6   5  20  -9]
 [-12   7  25   8]
 [ 15   5   7  23]]
[[ 12   3  30  31]
 [-18  -4 -11 -21]
 [ -6  -4   1  18]
 [ 27  25   7  22]]


In [ ]:
# standard deviation and variance
a = np.random.randint(-20, 30, (3, 4))
print(a)

print()
print(np.std(a, axis=0))
print(np.var(a, axis=0))

[[ 16   4 -13 -10]
 [ 22  29  -9  27]
 [ 23  -7   7  -6]]
[ 3.09120617 15.06283137  8.6409876  16.57977349]
[  9.55555556 226.88888889  74.66666667 274.88888889]


In [ ]:
a = np.random.randint(-20, 30, (3, 4))
print(a)

print()
np.corrcoef(a)

[[  9  26  24  -6]
 [ 21  27 -15  -4]
 [  2  27   3 -15]]



array([[1.        , 0.19083275, 0.85029126],
       [0.19083275, 1.        , 0.63939993],
       [0.85029126, 0.63939993, 1.        ]])

## Array manipulation

In [110]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([[11, 22, 33, 44], [55, 66, 77, 88]])

### Basic reshaping

In [ ]:
# transpose array

a.T
np.transpose(a)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [112]:
# flatten the array

a.flatten()
np.ravel(a) == np.reshape(a, -1)
# np.reshape(a,-1)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [54]:
# reshape array
# the shapes should match to perform reshape()
# 4*2 == 2*2*2

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(np.prod(np.shape(a)))

np.reshape(a, (2, 2, 2))

8


array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [55]:
# resize array
# similar to np.reshape(), but here the the shapes need not to be matched
# may add zeros or truncates depending upon the desired shape outcome

np.resize(a, (2, 6))
np.resize(a, (2, 2))

array([[1, 2],
       [3, 4]])

### Adding or Removing elements

In [ ]:
# append arrays

np.append(a, b) # without specifying axis will flatten the array

np.append(a, b, axis=1) # row wise append
# np.append(a, c, axis=0) # throws error as cols does not match

array([[ 1,  2,  3,  4, 11, 22, 33, 44],
       [ 5,  6,  7,  8, 55, 66, 77, 88]])

In [59]:
# insert into an array
# insert the value at the specified position
# shape is modified
# creates only view; does not assign/modify

print(a)

# numpy.insert(array, index, value, size=None)
np.insert(a, 8, 10) # if axis is none, array is flattened first
print(np.insert(a, 2, 10, axis=1))

[[1 2 3 4]
 [5 6 7 8]]
[[ 1  2 10  3  4]
 [ 5  6 10  7  8]]


In [ ]:
# delete from an array

# shape is modified
# creates only view; does not assign/modify

np.delete(a, 7) # if axis is none, array is flattened first
np.delete(a, 3, axis=1)

array([[1, 2, 3],
       [5, 6, 7]])

### Joining Arrays

```axis=0``` denotes rows\
```axis=1``` denotes cols

#### Joining 2d array along `axis=0`
* Return a 2d array containing rows of both the input arrays.\
* Both input arrays should have same number of cols
* Output array will have same number of cols

#### Joining 2d array along `axis=1`
* Return a 2d array M; where *r(i) = r(a) + r(b)*
* Both input arrays should have same number of rows
* Output array will have same number of rows

In [61]:
a = [1, 2, 3]
b = [4, 5, 6, 7]
c = [7, 8, 9]

d = [[1, 2, 3], [4, 5, 6]]
e = [[4, 5, 6], [7, 8, 9]]
f = [[1, 2], [3, 4]]

g = [ [ [11, 12, 13],
        [14, 15, 16] ],
      [ [21, 22, 23],
        [24, 25, 26] ],
      [ [31, 32, 33],
        [34, 35, 36] ]  ]
i = [ [ [11, 22, 33],
        [33, 44, 44] ],
      [ [55, 66, 55],
        [77, 88, 66] ],
      [ [99, 00, 77],
        [11, 22, 88] ]  ]

#### np.concatenate()
Add elements in second array to first array, according to same axis

In [81]:
# print(np.concatenate((a, b), axis=0))
# print(np.concatenate((a, b), axis=1)) # axis=1 is OutOfBound for 1D Array
# print(np.concatenate((a, c), axis=0))

# print()
# print(np.concatenate((d, e), axis=0))
# print(np.concatenate((d, e), axis=1))

# print()
# # print(np.concatenate((d, f), axis=0)) # cols mismatch between input arrays
# print(np.concatenate((d, f), axis=1))

# print()
# # print(np.concatenate((d, f), axis=0))
# print(np.concatenate((f, d), axis=1))

print(np.concatenate((g, i), axis=0)) # depth
print('\n\n')
print(np.concatenate((g, i), axis=1)) # row
print('\n\n')
print(np.concatenate((g, i), axis=2)) # col


[[[11 12 13]
  [14 15 16]]

 [[21 22 23]
  [24 25 26]]

 [[31 32 33]
  [34 35 36]]

 [[11 22 33]
  [33 44 44]]

 [[55 66 55]
  [77 88 66]]

 [[99  0 77]
  [11 22 88]]]



[[[11 12 13]
  [14 15 16]
  [11 22 33]
  [33 44 44]]

 [[21 22 23]
  [24 25 26]
  [55 66 55]
  [77 88 66]]

 [[31 32 33]
  [34 35 36]
  [99  0 77]
  [11 22 88]]]



[[[11 12 13 11 22 33]
  [14 15 16 33 44 44]]

 [[21 22 23 55 66 55]
  [24 25 26 77 88 66]]

 [[31 32 33 99  0 77]
  [34 35 36 11 22 88]]]


#### np.stack()
Creates a new dimension by joining the arrays\
Input arrays must have same shape
**bold text**
* if a.shape & b.shape is (x,y),\
  *np.stack((a,b), axis=0).shape* is (2,x,y)
* if a.shape & b.shape is (x,y),\
  *np.stack((a,b), axis=1).shape* is (x,2,y)
* if a.shape & b.shape is (x,y),\
  *np.stack((a,b), axis=2).shape* is (x,y,2)

In [76]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.stack((a, b), axis=0))
print(np.stack((a, b), axis=1))

print('\n\n')
c = np.array([[1, 2, 3], [4, 5, 6], [2, 6, 4]])
d = np.array([[4, 5, 6], [7, 8, 9], [5, 7, 8]])

# creates a new dimension with shape 2
print(np.stack((c,d), axis=0), np.shape(np.stack((c,d), axis=0)), sep='\n')
print('\n\n')
print(np.stack((c,d), axis=1), np.shape(np.stack((c,d), axis=1)), sep='\n')
print('\n\n')
print(np.stack((c,d), axis=2), np.shape(np.stack((c,d), axis=2)), sep='\n')

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]



[[[1 2 3]
  [4 5 6]
  [2 6 4]]

 [[4 5 6]
  [7 8 9]
  [5 7 8]]]
(2, 3, 3)



[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]

 [[2 6 4]
  [5 7 8]]]
(3, 2, 3)



[[[1 4]
  [2 5]
  [3 6]]

 [[4 7]
  [5 8]
  [6 9]]

 [[2 5]
  [6 7]
  [4 8]]]
(3, 3, 2)


#### np.vstack()
Append arrays vertically along first axis (`axis=0`)\
Should have same number of elements in every dimension except first dimension

* if a.shape and b.shape is (i,y,z) and (j,y,z);\
  *np.vstack((a,b)).shape* is (i+j, y, z)

In [100]:
# np.vstack()
# Append arrays vertically along first axis (axis=0)
# Should have same number of elements in every dimension except first dimension
# if a.shape and b.shape is (i,y,z) and (j,y,z);
#   np.vstack((a,b)).shape is (i+j, y, z)

a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))

print('\n\n')
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]],
              [[9, 0], [1, 2]], [[3, 4], [5, 6]]])  # (4,2,2)
d = np.array([[[5, 6], [7, 8]], [[9, 0], [1, 2]], [[3, 4], [5, 6]]]) # (3,2,2)
print(np.vstack((c, d)), np.vstack((c, d)).shape, sep='\n') # (7, 2, 2)

[[1 2]
 [3 4]]



[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]

 [[9 0]
  [1 2]]

 [[3 4]
  [5 6]]

 [[5 6]
  [7 8]]

 [[9 0]
  [1 2]]

 [[3 4]
  [5 6]]]
(7, 2, 2)


#### np.hstack()
Append arrays vertically along second axis (`axis=1`)\
Should have same number of elements in every dimension except second dimension

* if a.shape and b.shape is (x,i,z) and (x,j,z);\
  *np.hstack((a,b)).shape* is (x, i+j, z)

In [103]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.hstack((a, b)))

print('\n\n')
c = np.array([[[1, 2], [3, 4], [0, 0]], [[5, 6], [7, 8], [0, 0]],
              [[9, 0], [1, 2], [0, 0]]]) # (3,3,2)
d = np.array([[[5, 6], [7, 8]], [[9, 0], [1, 2]], [[3, 4], [5, 6]]]) # (3,2,2)
print(np.hstack((c, d)), np.hstack((c, d)).shape, sep='\n') # (3, 5, 2)

[1 2 3 4]



[[[1 2]
  [3 4]
  [0 0]
  [5 6]
  [7 8]]

 [[5 6]
  [7 8]
  [0 0]
  [9 0]
  [1 2]]

 [[9 0]
  [1 2]
  [0 0]
  [3 4]
  [5 6]]]
(3, 5, 2)


#### np.dstack()
Append arrays vertically along third axis (`axis=2`)\
Should have same number of elements in every dimension except third dimension

* if a.shape and b.shape is (x,y,i) and (x,y,j);\
  *np.dstack((a,b)).shape* is (x, y, i+j)

In [105]:
# np.dstack()
# Append arrays along third axis (axis=2)
# Should have same number of elements in every dimension except third dimension
# if a.shape and b.shape is (x,y,i) and (x,y,j);
#   np.vstack((a,b)).shape is (x, y, i+j)

a = np.array([1, 2])
b = np.array([3, 4])
print(np.dstack((a, b)))

print('\n\n')
c = np.array([[[1, 2, 0], [3, 4, 0]], [[5, 6, 0], [7, 8, 0]],
              [[9, 0, 0], [1, 2, 0]]]) # (3,2,3)
d = np.array([[[5, 6], [7, 8]], [[9, 0], [1, 2]], [[3, 4], [5, 6]]]) # (3,2,2)
print(np.dstack((c, d)), np.dstack((c, d)).shape, sep='\n') # (3, 2, 5)

[[[1 3]
  [2 4]]]



[[[1 2 0 5 6]
  [3 4 0 7 8]]

 [[5 6 0 9 0]
  [7 8 0 1 2]]

 [[9 0 0 3 4]
  [1 2 0 5 6]]]
(3, 2, 5)


---

In [ ]:
# np.r_[]
# np.c_[]

# np.row_stack() # np.vstack()
# np.column_stack()

Spliting arrays

In [ ]:
# hsplit(),

## Handling I/O